# Generated by Django 5.2.8 on 2025-11-15 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Mijoz ismi')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('size_chest', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Ko'krak (sm)")),
                ('size_waist', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bel (sm)')),
                ('size_height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Bo'y (sm)")),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha talablar")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlandi'), ('sewing', 'Tikish jarayonida'), ('finishing', 'Yakunlanmoqda'), ('done', 'Tayyor')], default='new', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='designs.design')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
