# Generated by Django 5.2.8 on 2025-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_fabric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Muddat (kun)'),
        ),
    ]
